# Generated by Django 3.1.7 on 2021-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20210426_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='picture',
        ),
        migrations.AddField(
            model_name='bank',
            name='image',
            field=models.ImageField(default='BanksPictures/default.png', upload_to='BanksPictures'),
        ),
        migrations.AddField(
            model_name='contract',
            name='image',
            field=models.ImageField(default='ContractsPictures/default.jpg', upload_to='ContractsPictures'),
        ),
    ]
