# Generated by Django 3.1.7 on 2021-05-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20210505_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов Великобритании'), ('JPY', 'Японская йена'), ('CHF', 'Швейцарский франк'), ('CNY', 'Китайский юань')], default='RUB', max_length=3, verbose_name='Базовая валюта'),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов Великобритании'), ('JPY', 'Японская йена'), ('CHF', 'Швейцарский франк'), ('CNY', 'Китайский юань')], default='RUB', max_length=3, verbose_name='Базовая валюта'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='CategoryPictures/default.jpg', upload_to='CategoryPictures'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов Великобритании'), ('JPY', 'Японская йена'), ('CHF', 'Швейцарский франк'), ('CNY', 'Китайский юань')], default='RUB', max_length=3, verbose_name='Базовая валюта'),
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов Великобритании'), ('JPY', 'Японская йена'), ('CHF', 'Швейцарский франк'), ('CNY', 'Китайский юань')], default='RUB', max_length=3, verbose_name='Базовая валюта'),
        ),
    ]
