# Generated by Django 3.1.7 on 2021-05-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20210505_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstrument',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='avgPrice',
            field=models.FloatField(null=True, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='interest',
            field=models.FloatField(null=True, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='stockID',
            field=models.ManyToManyField(null=True, to='accounting.Stock'),
        ),
    ]
