# Generated by Django 3.1.7 on 2021-05-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20210505_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='parentOperationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.operation'),
        ),
    ]
