# Generated by Django 3.1.7 on 2021-05-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_auto_20210505_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='toFinancialInstrumentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toFinancialInstrument', to='accounting.financialinstrument'),
        ),
    ]
