# Generated by Django 3.1.7 on 2021-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_auto_20210505_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstrument',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Количество'),
        ),
    ]
