# Generated by Django 3.1.7 on 2021-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_auto_20210506_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstrument',
            name='type',
            field=models.CharField(choices=[('B', 'Банковский'), ('I', 'Инвестиционный'), ('С', 'Валюта')], max_length=1, verbose_name='Тип финансового инструмента'),
        ),
    ]
