# Generated by Django 3.1.7 on 2021-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_auto_20210509_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('S', 'Расходы'), ('I', 'Доходы'), ('T', 'Переводы')], default='S', max_length=1, verbose_name='Тип категории'),
        ),
    ]
