# Generated by Django 3.1.7 on 2021-05-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('S', 'Spending'), ('I', 'Income'), ('TRANS', 'Transfer'), ('BS', 'Buying a stock'), ('SS', 'Sale of stock'), ('DIV', 'Dividends')], max_length=5, verbose_name='Тип операции'),
        ),
    ]
