# Generated by Django 3.1.7 on 2021-05-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_auto_20210514_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinstrument',
            name='interest',
        ),
    ]
