# Generated by Django 3.1.7 on 2021-05-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_auto_20210514_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialinstrument',
            name='stockID',
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='stockID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.stock'),
        ),
    ]
