# Generated by Django 3.1.7 on 2021-05-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_auto_20210515_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
