# Generated by Django 3.1.7 on 2021-05-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
