# Generated by Django 3.1.7 on 2021-05-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_auto_20210526_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='type',
        ),
    ]
